import '../styles/globals.css'
import Navbar from '../components/Navbar'
import Head from 'next/head'


function MyApp({ Component, pageProps }) {

  return(
    <div>
      <Head>
        <title>Pokedex</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/pokeball.ico" />
      </Head>
      <Navbar/>
      <Component {...pageProps} />
    </div>
  ) 
}

export default MyApp
